name: Issues Trigger

on: 
  issues: 
    types:
      - opened
      - deleted
      - reopened
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  issues-react:
    runs-on:  ubuntu-latest
    steps:
      - name: Print details about the issue
        run: | 
          echo "user: ${{ toJSON(github.event.issue.user) }}"
          echo "action: ${{ toJSON(github.event.action) }}"
          echo "event: ${{ toJSON(github.event) }}"
          echo "everything: ${{ toJSON(github) }}"
