name: Issues Trigger

on: 
  pull_request: 
    types:
      - opened
      - reopened
  workflow_dispatch:

env:
  PROTON_PR_STARTING_STRING: "Update requested for Proton"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  issues-react:
    runs-on:  ubuntu-latest
    steps:
      - name: Print details about the issue
        run: | 
          echo "event: ${{ toJSON(github.event) }}"
          echo "everything: ${{ toJSON(github) }}"
          echo "title: ${{ toJSON(github.event.pull_request.title) }}"
      
      - name: add labels
        if: ${{ startsWith(github.event.pull_request.title, env.PROTON_PR_STARTING_STRING) }}
        run: |
          echo "if is met"
