name: Issues Trigger

on: 
  issues: 
    types:
      - opened
      - deleted
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  issues-react:
    runs-on:  ubuntu-latest
    steps:
      - name: Print details about the issue
        run: | 
          echo "${{ toJSON(github.event.issue.user) }}"
          echo "${{ toJSON(github.event.action) }}"